"""Generate the BMVC method overview figure (Fig 2 by source order).

Two panels in a single figure*:
  (a) ITB construction pipeline: datasets -> degradation -> VisiScore-Net -> ITB strata
  (b) QCTS architecture: frozen backbone + frozen quality scorer -> T(q-bar) -> softmax

This script produces a starting SVG that the user refines in Illustrator. The
PDF is regenerated by ``project/scripts/svg_to_pdf.py``.
"""
from __future__ import annotations

import pathlib
import sys

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

OUT_DIR = pathlib.Path("project/meeting/BMVC/figures")
OUT_SVG = OUT_DIR / "fig_method.svg"
OUT_PDF = OUT_DIR / "fig_method.pdf"

# Colour palette consistent with fig2_problem (Quality-Aware green)
FROZEN_FC = "#dcdcdc"
FROZEN_EC = "#4a4a4a"
LEARN_FC = "#a8d5a8"
LEARN_EC = "#2c602c"
DATA_FC = "#e8e8f0"
DATA_EC = "#3a4a6a"
STRAT_FC = "#e0f0e8"
STRAT_EC = "#2c602c"
OP_FC = "#fff5b8"
OP_EC = "#7a6a1a"
ARROW = "#404040"


def _box(ax, xy, w, h, fc, ec, lw=1.2, rounding=0.06):
    p = FancyBboxPatch(
        (xy[0], xy[1]), w, h,
        boxstyle=f"round,pad=0.02,rounding_size={rounding}",
        fc=fc, ec=ec, lw=lw,
    )
    ax.add_patch(p)
    return p


def _arrow(ax, src, dst, lw=1.3, color=ARROW, style="->", mut=14):
    a = FancyArrowPatch(src, dst, arrowstyle=style, mutation_scale=mut,
                        color=color, lw=lw, shrinkA=2, shrinkB=2)
    ax.add_patch(a)
    return a


def panel_a(ax):
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.axis("off")
    ax.text(0.0, 5.85, "(a)  ITB construction", fontsize=11, fontweight="bold",
            ha="left", va="bottom")

    # Datasets
    _box(ax, (0.05, 1.4), 1.85, 3.0, DATA_FC, DATA_EC)
    ax.text(0.975, 4.05, "Raw datasets", ha="center", fontsize=9, fontweight="bold")
    ax.text(0.975, 3.4,
            "ISIC 2020\nFitzPatrick17k\nHAM10000\nPAD-UFES",
            ha="center", fontsize=8, linespacing=1.4)
    ax.text(0.975, 1.75, "$\\sim$45k images", ha="center",
            fontsize=8, style="italic", color="#555")

    # Degradation
    _box(ax, (2.25, 0.9), 2.05, 4.0, FROZEN_FC, FROZEN_EC)
    ax.text(3.275, 4.55, "Programmatic\ndegradation",
            ha="center", fontsize=9, fontweight="bold", linespacing=1.2)
    ax.text(3.275, 2.7,
            "$q_1$  sharpness\n$q_2$  brightness\n$q_3$  completeness\n"
            "$q_4$  colour temp.\n$q_5$  contrast",
            ha="center", fontsize=7.8, linespacing=1.6)

    # VisiScore-Net
    _box(ax, (4.65, 1.4), 2.05, 3.0, FROZEN_FC, FROZEN_EC)
    ax.text(5.675, 4.05, "VisiScore-Net", ha="center", fontsize=9, fontweight="bold")
    ax.text(5.675, 3.6, "(frozen, 5-head IQA)",
            ha="center", fontsize=7.8, style="italic")
    ax.text(5.675, 2.7, "$q \\in [0,1]^5$", ha="center", fontsize=9.5)
    ax.text(5.675, 2.1, "$\\bar q = \\frac{1}{5}\\sum_i q_i$",
            ha="center", fontsize=9.5)

    # ITB strata
    _box(ax, (7.05, 0.7), 2.85, 4.4, STRAT_FC, STRAT_EC)
    ax.text(8.475, 4.75, "ITB strata", ha="center", fontsize=9, fontweight="bold")
    ax.text(8.475, 4.05, "LQ ($\\bar q\\!<\\!0.45$, $n{=}300$)",
            ha="center", fontsize=7.9)
    ax.text(8.475, 3.5, "Edge ($0.45$–$0.50$, $n{=}660$)",
            ha="center", fontsize=7.9)
    ax.text(8.475, 2.95, "HQ ($\\bar q\\!>\\!0.50$, $n{=}360$)",
            ha="center", fontsize=7.9)
    ax.text(8.475, 2.4, "Diverse ($n{=}1{,}500$)",
            ha="center", fontsize=7.9)
    ax.text(8.475, 1.25, "149{,}100 quality\nannotations total",
            ha="center", fontsize=7.5, style="italic", color="#555")

    # Connecting arrows
    for x0, x1 in [(1.95, 2.25), (4.30, 4.65), (6.70, 7.05)]:
        _arrow(ax, (x0, 2.9), (x1, 2.9))


def panel_b(ax):
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 6)
    ax.axis("off")
    ax.text(0.0, 5.85, "(b)  QCTS architecture", fontsize=11, fontweight="bold",
            ha="left", va="bottom")

    # Inputs (single x branching)
    ax.text(0.25, 4.45, "$x$", fontsize=12, ha="center", va="center")
    ax.text(0.25, 1.65, "$x$", fontsize=12, ha="center", va="center")

    # Backbone (top)
    _box(ax, (0.65, 3.55), 3.4, 1.95, FROZEN_FC, FROZEN_EC)
    ax.text(2.35, 4.95, "Frozen Std VIB backbone",
            ha="center", fontsize=9, fontweight="bold")
    ax.text(2.35, 4.35, "EfficientNet-B3", ha="center", fontsize=8)
    ax.text(2.35, 3.95, "+ VIB encoder", ha="center", fontsize=8)

    # VisiScore (bottom)
    _box(ax, (0.65, 0.65), 3.4, 1.95, FROZEN_FC, FROZEN_EC)
    ax.text(2.35, 2.05, "VisiScore-Net (frozen)",
            ha="center", fontsize=9, fontweight="bold")
    ax.text(2.35, 1.35, "5-head IQA $\\to \\bar q$",
            ha="center", fontsize=8.5)

    # Logits z
    ax.text(4.6, 4.75, "$z \\in \\mathbb{R}^K$",
            ha="center", fontsize=10)
    # qbar
    ax.text(4.6, 1.85, "$\\bar q$", ha="center", fontsize=11)

    # T(qbar) learnable
    _box(ax, (5.15, 2.5), 2.55, 1.5, LEARN_FC, LEARN_EC, lw=1.6)
    ax.text(6.425, 3.55, "$T(\\bar q)$",
            ha="center", fontsize=11, fontweight="bold")
    ax.text(6.425, 2.95,
            "$=\\mathrm{softplus}(T_0 + \\alpha(1{-}\\bar q))$",
            ha="center", fontsize=8.5)

    # softmax op
    _box(ax, (8.0, 2.95), 1.7, 1.0, OP_FC, OP_EC, lw=1.0, rounding=0.04)
    ax.text(8.85, 3.55, "softmax", ha="center", fontsize=9, fontweight="bold")
    ax.text(8.85, 3.15, "$(z / T(\\bar q))$",
            ha="center", fontsize=8.5)

    # Output p
    ax.text(8.85, 2.35, "$\\to\\;p$", ha="center", fontsize=12, fontweight="bold")

    # Arrows
    # x -> backbone
    _arrow(ax, (0.40, 4.45), (0.65, 4.45))
    # x -> visiscore
    _arrow(ax, (0.40, 1.65), (0.65, 1.65))
    # backbone -> z label -> softmax
    _arrow(ax, (4.05, 4.45), (4.40, 4.65))  # short to z
    _arrow(ax, (4.85, 4.65), (8.10, 3.85))  # z to softmax (slanted)
    # visiscore -> qbar -> T
    _arrow(ax, (4.05, 1.65), (4.45, 1.78))
    _arrow(ax, (4.80, 1.95), (5.50, 2.55))  # qbar -> T (slanted up)
    # T -> softmax
    _arrow(ax, (7.70, 3.40), (8.00, 3.40))
    # softmax -> p
    _arrow(ax, (8.85, 2.85), (8.85, 2.55))

    # Footnote
    ax.text(5.0, 0.05,
            "Learnable: $(T_0,\\alpha)$ — 2 params, no retraining. "
            "$\\alpha\\!=\\!0$ recovers standard TS.",
            ha="center", fontsize=8.2, style="italic", color=LEARN_EC)


def main() -> int:
    if not OUT_DIR.is_dir():
        print(f"[ERR] {OUT_DIR.resolve()} not found", file=sys.stderr)
        return 1

    fig = plt.figure(figsize=(14, 4.6))
    gs = fig.add_gridspec(1, 2, width_ratios=[1.05, 1.0], wspace=0.10,
                          left=0.01, right=0.99, top=0.97, bottom=0.03)
    panel_a(fig.add_subplot(gs[0, 0]))
    panel_b(fig.add_subplot(gs[0, 1]))

    fig.savefig(OUT_SVG, bbox_inches="tight", pad_inches=0.05)
    fig.savefig(OUT_PDF, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)
    print(f"[OK] wrote {OUT_SVG.name}  ({OUT_SVG.stat().st_size // 1024} KB)")
    print(f"[OK] wrote {OUT_PDF.name}  ({OUT_PDF.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
